/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const gbConfig: (typeof import('../config/_expose/index'))['gbConfig']
  const gbLocale: (typeof import('../locale/_expose/index'))['gbLocale']
  const gbStore: (typeof import('../store/_expose/index'))['gbStore']
  const gbUtil: (typeof import('../util/_expose/index'))['gbUtil']
}
